name: gemini_api_flutter
description: "A Flutter package that simplifies interacting with the Gemini API, enabling content generation, chat, and multimodal AI capabilities in your apps."
version: 0.0.6
homepage: https://github.com/nikhil-7-ninja/gemini_api_flutter
repository: https://github.com/nikhil-7-ninja/gemini_api_flutter
issue_tracker: https://github.com/nikhil-7-ninja/gemini_api_flutter/issues
environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
